### ISSUE TITLE
 Jacobian matrix H

### ISSUE THREAD

**Issue by a-github-learner** [Ji1Xingyu/lio_gvm#4]
Nice work！
II have a question about how to obtain the Jacobian matrix $\boldsymbol{H}_{k,j}^n$？Looking forward to your response.

**Comment by Ji1Xingyu** [comment]
Please see attached for the derivation of the Jacobian matrix. Also I have updated the sup_material.pdf to include this derivation.
![2024-05-06_19-12](https://github.com/Ji1Xingyu/lio_gvm/assets/89335767/bc51779f-91af-4902-889c-1fa6d286f612)

**Comment by a-github-learner** [comment]
Thank you for your timely reply and detailed derivation! I have two additional questions:
1. Dose  $^{L_{k}}\boldsymbol{p}_j$ in your sup_material.pdf has the same meaning as $^G\mathbf{\hat{\mu}}_j^n$, which means the centroid of the voxel? Or it simply denote the position of points in the global frame?
2. In $\left(\Lambda_j^n\right)^{-1}=\left(\mathbf{Q}_j^n\right)^T \mathbf{V}_k^{-1} \mathbf{Q}_j^n$, since $\mathbf{V}_k$ is a diagonal matrix,  how is matrix decomposition performed on it? Is $\mathbf{Q}_j^n$ an identity matrix？

**Comment by Ji1Xingyu** [comment]
1. ${}^G\hat{\boldsymbol{p}}_j$ denotes the point ${}^{L_k}\hat{\boldsymbol{p}}_j$ after being transformed to the global frame.
2. Actually, the matrix decomposition is performed on $\left( {\Lambda}_j^n \right)^{-1}$. Moreover, since it is a diagonal matrix, this decomposition can be simplified as solving the following equation on each diagonal element: $q_k = \sqrt{\frac{v_k}{\lambda_k}}$.
